### ISSUE TITLE
HTTP 409

### ISSUE THREAD

**Issue by yesyesiamkamil** [vanutp/tgbridge#1]
When i start server with TGBridge active i noticed this error in console. The only solution to not getting the 409 error is disabling the mod. Also the bot doesnt redirect telegram chat messages to > game, but redirecting messages from game to > telegram chat. How i can fis that issue? It's a great mod and i really want to use it on my server. 

[13:15:12] [Thread-30/INFO]: WebServer started.
[13:15:12] [BlueMap-Plugin-Loading/INFO]: BlueMap loaded!
[13:15:15] [DefaultDispatcher-worker-2/ERROR]: HTTP 409 
[13:15:16] [DefaultDispatcher-worker-5/ERROR]: HTTP 409 
[13:15:20] [DefaultDispatcher-worker-9/ERROR]: HTTP 409 
[13:15:21] [DefaultDispatcher-worker-5/ERROR]: HTTP 409 
[13:15:25] [DefaultDispatcher-worker-1/ERROR]: HTTP 409 
[13:15:26] [DefaultDispatcher-worker-7/ERROR]: HTTP 409 
[13:15:30] [DefaultDispatcher-worker-1/ERROR]: HTTP 409 
[13:15:31] [DefaultDispatcher-worker-1/ERROR]: HTTP 409 
[13:15:35] [DefaultDispatcher-worker-6/ERROR]: HTTP 409 
[13:15:37] [DefaultDispatcher-worker-7/ERROR]: HTTP 409 

![Screenshot_319](https://github.com/vanutp/tgbridge/assets/31569579/9e4c0155-2d1d-4ecd-be87-767ce8c6449c)

Config:

```
# It's enough to set botToken and chatId for the plugin to work.
# When your group has topics enabled, you should also set topicId.
general:
  # Open https://t.me/BotFather to create a bot.
  # Make sure to *disable* group privacy in the "Bot Settings" menu.
  botToken: "XXXXXXXXXXXXXXXXX" (hidden)
  # To get the chat id, right click/tap on any message and choose "Copy Message Link".
  # If there is no such option, enable "Chat history for new members" in the group settings.
  # It can then be disabled.
  # The copied link will be in the format "https://t.me/c/<chat_id>/<topic_id>/<message_id>".
  # Topic id will only be present if the chat has topics enabled.
  chatId: -1002236234246
  # If the specified chat has topics enabled, specify the id of the topic that will be
  # synchronized with the game. Commands will have no effect in other topics.
  # If you don't set this, the bot will send all messages to the "General" topic
  # and the /list command will have weird behaviour when sent in other topics.
  # Default value: null (disabled)
  topicId: null
messages:
  # If this value is set, waypoints shared from Xaero's Minimap/World Map will be rendered
  # as links to a specified Bluemap instance.
  # Note that shared waypoints will be sent regardless of the requirePrefixInMinecraft setting.
  # Example: https://map.example.com
  # Default value: null (disabled)
  bluemapUrl: "XXXXXXXXX" (hidden)
  # If this value is set, messages without specified prefix won't be forwarded to Telegram.
  # Example: "!" (quotes are required)
  # Default value: "" (disabled)
  requirePrefixInMinecraft: ""
  # Chat messages sent within the specified interval (in seconds) will be merged in one.
  # The value is specified in seconds
  # Default value: 0 (disabled)
  mergeWindow: 0
events:
  advancementMessages:
    enable: true
    # Include advancement descriptions in Telegram messages
    showDescription: true
  enableDeathMessages: true
  enableJoinMessages: true
  enableLeaveMessages: true
  # If a player leaves and then joins within the specified time interval (in seconds),
  # the leave and join messages will be deleted.
  # This is useful when players frequently re-join, for example because of connection problems.
  # Only has effect when both enableJoinMessages and enableLeaveMessages are set to true
  # The value is specified in seconds
  # Default value: 0 (disabled)
  leaveJoinMergeWindow: 0

```

**Comment by vanutp** [comment]
Hi! 409 means you have started another program with the same bot token. Have you used this token anywhere else? Maybe another server is running? In that case you'll need to create a bot per server.
This is a Telegram Bot API limitation

**Comment by yesyesiamkamil** [comment]
Hi again!

This is a strange behavior, but I found a solution. Open the link in your browser https://api.telegram.org/bot<BOT TOKEN>/deleteWebhook. After deleting webhook everything works as it should. 

I think it makes sense to add this information to the documentation. Thanks again for the great mod!

**Comment by vanutp** [comment]
Thanks! I made the plugin remove the webhook automatically on startup
