### ISSUE TITLE
messages are not transmitted from telegram to the game

### ISSUE THREAD

**Issue by hapugov** [vanutp/tgbridge#21]
Hello, I encountered a problem that messages from the telegram chat are not transferred to the game. But messages come from the telegram game. 

Telegram Bridge v0.4.4

Current Purpur Version: 1.21.1-2291-bba87bf (MC: 1.21.1)*
* You are 33 version(s) behind
Download the new version at: https://purpurmc.org/downloads
Previous: 1.21-2280-930003b (MC: 1.21)

**Comment by vanutp** [comment]
Could you post the logs?

**Comment by hapugov** [comment]
The plugin does not write logs, and there is silence in the server console when I send a message from a telegram

**Comment by vanutp** [comment]
Are there any messages at startup?
Can you reproduce this with only tgbridge installed?

**Comment by hapugov** [comment]
Yes, there are messages from the plugin that it has been launched successfully, there are no errors or warnings from it

I've now run some tests.
1. I launched a server on Windows 10 with one lpagin - It works.
2. I launched a server on Windows 10 with the entire set of plugins - it works

3. I launched a server with one plugin on Linux (where the plugin does not work) - it does not work
4. I launched a server with all the plugins on Linux (where the plugin does not work) - it does not work

windows:

version 21h2 (19044.2130 )

java version "21.0.2" 2024-01-16 LTS
Java(TM) SE Runtime Environment (build 21.0.2+13-LTS-58)
Java HotSpot(TM) 64-Bit Server VM (build 21.0.2+13-LTS-58, mixed mode, sharing)

Llinux server:

Ubuntu 22.04.4 LTS

openjdk version "21.0.4" 2024-07-16 LTS
OpenJDK Runtime Environment Temurin-21.0.4+7 (build 21.0.4+7-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.4+7 (build 21.0.4+7-LTS, mixed mode, sharing)

**Comment by vanutp** [comment]
Works for me on Ubuntu 22.04.5, Temurin-21.0.4+7 and Purpur 1.21.1-2324-ver/1.21.1@e12a4de.
Did you use the same bot for both servers? Maybe you didn't disable group privacy

**Comment by hapugov** [comment]
God, I'm sorry for wasting your time, the problem was on my side. The bot did not have access to messages.

Thank you for your assistance, it’s not every day that I set up telegram applications

**Comment by vanutp** [comment]
No problem :)
