### ISSUE TITLE
Make instructions for disabling group privacy more clear

### ISSUE THREAD

**Issue by KosyakMakc** [vanutp/tgbridge#24]
Messages from game in tg - OK
Messages from tg in game - only system messages will be sent
![image](https://github.com/user-attachments/assets/bd1c4191-aba2-4c45-9096-a1b3f109ca54)

**Comment by KosyakMakc** [comment]
P.S. Errors in console to ignore - it was another issue)

**Comment by KosyakMakc** [comment]
Im checked #21 - enable admin roles and messages sent to the game!
Please update instructions and it issue can be closed

**Comment by vanutp** [comment]
The instructions already specify that you should disable group privacy in BotFather. I will try to make it more clear

**Comment by MeteoraCD2** [comment]
> Im checked #21 - enable admin roles and messages sent to the game! Please update instructions and it issue can be closed

Hello! Tell me, what exactly did you do? Messages from Telegram appear in the server console, but players do not see them in chat
