### ISSUE TITLE
Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

### ISSUE THREAD

**Issue by MeteoraCD2** [vanutp/tgbridge#28]
Hi!
Paper 1.20.1
My server log: [latest.log](https://github.com/user-attachments/files/17451786/latest.log)
Error: [00:03:07] [DefaultDispatcher-worker-3/ERROR]: [tgbridge] Telegram exception: {"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}
In case it matters: I have multiple servers. I use one telegram bot for all server chats. All server chats are in one group in different topics.

**Comment by vanutp** [comment]
Unfortunately, you won't be able to use one bot for multiple servers. It's a Telegram Bot API limitation.

**Comment by MeteoraCD2** [comment]
> Unfortunately, you won't be able to easily use one bot for multiple servers. It's a Telegram Bot API limitation.

Thank you! This is indeed true. I created different bots for different servers, and everything works.
This should be written in the installation description :)
