### ISSUE TITLE
Suddenly stops working

### ISSUE THREAD

**Issue by yesyesiamkamil** [vanutp/tgbridge#3]
Noticed that in the evening when many of users online (something about 10 people) and server experience high load — mod stops working. To restart the mod you need to restart the entire server.
See no errors messages by tgbridge in console or smth.  

Below the full list of mods on server. Fabric 1.20.1. Already trying to just /tgbridge reload or deleteWebhook but it doesnt help.

AdditionalStructures-1.20.x-(v.4.2.1) 
alternate-current-mc1.20-1.7.0 
animal_feeding_trough-1.1.0+1.20.1 
appleskin-fabric-mc1.20.1-2.5.1 
Aquamirae-6 
architectury-9.2.14-fabric 
artifacts-fabric-9.5.10 
azurelib-fabric-1.20.1-2.0.25 
balm-fabric-1.20.1-7.3.4 
betterarcheology-1.1.9-1.20.1 
bettercombat-fabric-1.8.5+1.20.1 
bettervillage-fabric-1.20.1-3.2.0 
BlueMap-3.21-fabric-1.20 
botarium-fabric-1.20.1-2.3.3 
cardinal-components-api-5.2.2 
Chunky-1.3.146 
cloth-config-11.1.118-fabric 
collective-1.20.1-7.61 
comforts-fabric-6.3.5+1.20.1 
coroutil-fabric-1.20.1-1.3.7 
create-fabric-0.5.1-f-build.1417+mc1.20.1 
create-food-1.0.7-fabric 
create-new-age-fabric-1.20.1-1.1.2 
create-track-map-1.4+mc1.20.1-fabric 
createdeco-2.0.2-1.20.1-fabric 
CreateNumismatics-1.0.6+fabric-mc1.20.1 
createoreexcavation-fabric-1.20-1.4.6 
create_jetpack-fabric-4.2.0 
cristellib-1.1.5-fabric 
ctov-fabric-3.4.3 
ctov-farmers-delight-compat-2.1 
Display Case-fabric-1.20-1.0.8 
DungeonsArise-1.20.1-2.1.57-fabric-release 
easyauth-mc1.20-3.0.19 
easywhitelist-mc1.20-rc1-1.0.1 
endermanoverhaul-fabric-1.20.1-1.0.4 
explosive-enhancement-1.2.2-1.20.x 
fabric-api-0.92.2+1.20.1 
fabric-carpet-1.20-1.4.112+v230608 
fabric-language-kotlin-1.11.0+kotlin.2.0.0 
FarmersDelight-1.20.1-2.1.1+refabricated 
farmersknives-3.2 
ferritecore-6.0.1-fabric 
ForgeConfigAPIPort-v8.0.0-1.20.1-Fabric 
furnacerecycle-1.20.1-2.2 
geckolib-fabric-1.20.1-4.4.6 
grieflogger-1.1.2-fabric 
handcrafted-fabric-1.20.1-3.0.6 
Highlighter-1.20.1-fabric-1.1.9 
highspeed-rail-0.4.0+1.20.1 
HWGMod-1.20.1-2.0.2 
Iceberg-1.20.1-fabric-1.1.18 
ImmediatelyFast-Fabric-1.2.17+1.20.4 
immersive_aircraft-1.0.1+1.20.1-fabric 
immersive_armors-1.6.1+1.20.1-fabric 
immersive_paintings-0.6.7+1.20.1-fabric 
indium-1.0.31+mc1.20.4 
interiors-0.5.3+fabric-mc1.20.1 
InventorySorter-1.9.0-1.20 
iris-1.7.0+mc1.20.1 
iris-flywheel-compat-1.20.1-0.2.5 
Jade-1.20-fabric-11.9.2 
krypton-0.2.3 
letsdo-API-fabric-1.2.13-fabric 
letsdo-brewery-fabric-1.1.8 
letsdo-vinery-fabric-1.4.22 
libraryferret-fabric-1.20.1-4.0.0 
lithium-fabric-mc1.20.1-0.11.2 
lithostitched-fabric-1.20.1-1.1.5 
livingthings-fabric-1.20.1-2.0.2 
man_of_many_planes-0.1.0+1.20.1-fabric 
mcw-bridges-3.0.0-mc1.20.1fabric 
mcw-doors-1.1.0fabric-mc1.20.1 
mcw-furniture-3.2.2-mc1.20.1fabric 
mcw-windows-2.2.1-mc1.20.1fabric 
medievalorigins-6.3.10+1.20.1 
memoryleakfix-fabric-1.17+-1.1.5 
minecraft-comes-alive-7.5.18+1.20.1-universal 
MobCaptains-v3.1.2 
modmenu-7.2.2 
molten_metals-1.20.1-0.1.4-fabric 
moonlight-1.20-2.11.33-fabric 
morefrogs-1.20.1-1.2.5-fabric 
moremobvariants-fabric+1.20.1-1.3.0.1 
more_mobs-v1.5.1-mc1.14x-1.20x-mod 
mru-0.4.2+1.20.1 
noisium-fabric-2.0.3+mc1.20-1.20.1 
npc-variety-1.20.4-2.3.0 
Obscure-API-16 
Origins-1.20.1-1.10.0 
owo-lib-0.11.0+1.20 
Pehkui-3.8.2+1.14.4-1.20.6 
player-animation-lib-fabric-1.0.2-rc1+1.20 
polymorph-fabric-0.49.5+1.20.1 
RecipeCooldown-1.0.0 
resourcefulconfig-fabric-1.20.1-2.1.2 
resourcefullib-fabric-1.20.1-2.1.25 
RoughlyEnoughItems-12.1.725-fabric 
simplyswords-fabric-1.55.0-1.20.1 
sliceanddice-fabric-3.2.1 
SmartBrainLib-fabric-1.20.1-1.14 
sodium-fabric-0.5.8+mc1.20.1 
Sounds-0.8.1+1.20.1 
spark-1.10.53-fabric 
spell_power-0.10.2+1.20.1 
starterkit-1.20.1-6.7 
Steam_Rails-1.6.4+fabric-mc1.20.1 
supermartijn642configlib-1.1.8a-fabric-mc1.20 
tectonic-fabric-1.20-2.3.5b 
TerraBlender-fabric-1.20.1-3.0.1.7 
Terralith_1.20_v2.5.1 
tgbridge-0.3-fabric-1.20.1 
The_Graveyard_3.1_(FABRIC)_for_1.20.1 
Towns-and-Towers-1.12-Fabric+Forge 
travelersbackpack-fabric-1.20.1-9.1.13 
treeharvester-1.20.1-8.7 
trinkets-3.7.2 
UndergroundBunkers-1.0.3-1.19.2-1.20.4-fabric 
vmp-fabric-mc1.20.1-0.2.0+beta.7.102-all 
voicechat-fabric-1.20.1-2.5.15 
watut-fabric-1.20.1-1.1.1 
waystones-fabric-1.20-14.1.3 
worldborder-1.20.1-4.4 
XaerosWorldMap_1.38.8_Fabric_1.20 
Xaeros_Minimap_24.2.0_Fabric_1.20 
youre-in-grave-danger-2.0.0-beta.13 
YungsApi-1.20-Fabric-4.0.5 

Im also using the startup arguments:
java -Xms128M -XX:MaxRAMPercentage=95.0 -Dterminal.jline=false -Dterminal.ansi=true --add-modules=jdk.incubator.vector -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -XX:G1NewSizePercent=40 -XX:G1MaxNewSizePercent=50 -XX:G1HeapRegionSize=16M -XX:G1ReservePercent=15 $( [[ ! -f unix_args.txt ]] && printf %s "-jar server.jar" || printf %s "@unix_args.txt" )

**Comment by yesyesiamkamil** [comment]
One more thing: if i reloading server TGbridge succuessfully sending message «Server stopped» to Telegram. So it seems the problem only with message forwarding mechanism from TG to MC and from MC to TG.

After reloading server all works fine for ~5-6 hours.

**Comment by vanutp** [comment]
[tgbridge-0.4.2-dev-fabric-1.20.1-1.20.4.jar.zip](https://github.com/user-attachments/files/15844135/tgbridge-0.4.2-dev-fabric-1.20.1-1.20.4.jar.zip)
Please try to reproduce the problem with this version and send me the log (or only lines with `(tgbridge)` in it). I have added verbose logging to this version to help diagnose the problem. Also the `/tgbridge reload` command should now try to fix the problem.

**Comment by yesyesiamkamil** [comment]
Thanks a lot! Already added on my server. I'll get back soon.

**Comment by yesyesiamkamil** [comment]
This time the mod worked for almost 24 hours without problems, but at about 19:00 it stopped forwarding messages again.
Here is a fragment of the log from the Logs folder (latest.log file) for 4 hours before the failure. /tgbridge reload doesn't help
![Screenshot_341](https://github.com/vanutp/tgbridge/assets/31569579/8805b737-5220-473b-9483-b5be15d4a6de)


[[DefaultDispatcher-worker-.txt](https://github.com/user-attachments/files/15859124/DefaultDispatcher-worker-.txt)

**Comment by vanutp** [comment]
Thanks! I have released a new version (0.4.2) with the fix

**Comment by yesyesiamkamil** [comment]
Everything works fine just before i install C2ME (today in between 21-22:00). Now i've hot that issue again and /tgbridge reload doesnt help. TGbridge stops working at ~22:47

[latest.log](https://github.com/user-attachments/files/15892039/latest.log)

**Comment by vanutp** [comment]
That doesn't look like an issue with tgbridge. I don't use random in the mod at all
