### ISSUE TITLE
FR: Allow whitelisting from Telegram

### ISSUE THREAD

**Issue by purrloftruth** [vanutp/tgbridge#35]
It would be very nice if the mod had a function to allow whitelisting new players directly from telegram.

In my case, the server is for a small group, so it would be okay if each player could whitelist themselves using a command. (It would make sense for each chatter to only be able to whitelist one particular Minecraft account at a time.) I'm sure there are larger groups though where they may want the ability to whitelist restricted only to group admins.

Thanks for your hard work!

**Comment by vanutp** [comment]
Hi! A feature to link Telegram and Minecraft accounts is tracked in #16, I plan implement group-based whitelisting using this system. But it's unlikely to have an easy setup, or at least it's not a priority.
There is also #32, but that's not really what you want.
