### ISSUE TITLE
Support for 1.21

### ISSUE THREAD

**Issue by arsel-5lvxa7b1** [vanutp/tgbridge#4]
Hello! I'm once again asking for a new version lol. If I can help in some way, let me know. I'm trying to update another mod to 1.21 and it's been a challenge :)

**Comment by vanutp** [comment]
1.20.6 build did actually run on 1.21 without changes. Changed supported versions and published as 0.4.3 :)

**Comment by arsel-5lvxa7b1** [comment]
Thank you!
