### ISSUE TITLE
Vanish

### ISSUE THREAD

**Issue by Ter224** [vanutp/tgbridge#40]
Добрый день. Буду крайне признателен за добавление такой функции, как скрытие некоторых ников при входе/выходе из сервера, и из списка /list

С ванишем, думаю, непросто будет это сделать. А с обычным списком ников - попроще. 
Спасибо за Ваш труд и создание данного плагина!

========================

Good afternoon. I would be extremely grateful for the addition of such a feature as hiding some nicknames when logging in/out of the server and from the list

With Vanish, I think it will not be easy to do this. And with the usual list of nicknames, it's easier. 
Thank you for your hard work and the creation of this plugin!

**Comment by vanutp** [comment]
Added support for some vanish plugins: https://github.com/vanutp/tgbridge#compatibility. Will be available in the next release

**Comment by vanutp** [comment]
Выложил версию 0.6.0

**Comment by Ter224** [comment]
У нас используется CMI. Буду крайне благодарен за добавление его ваниша. Спасибо большое

**Comment by vanutp** [comment]
К сожалению не получится просто его добавить, т.к. авторы не публикуют API в репозиторий. Открыл отдельную issue #49. Сам делать в ближайшее время не планирую, но PR приму.
