### ISSUE TITLE
Enhancement — linking a Discord account to a Minecraft account

### ISSUE THREAD

**Issue by CalebMy** [vanutp/tgbridge#43]
Your plugin for syncing Telegram chat and Minecraft server is an alternative to a similar plugin for syncing Discord and Minecraft server
The Discord sync plugin had a function to link the Discord account to the Minecraft account (to filter player traffic from bots)
Is it possible to implement such functionality in your plugin?

И на русском

Ваш плагин на синхронизацию чата Telegram и Minecraft сервер - альтернатива подобного плагина на синхронизацию Discord и Minecraft сервер

В плагине на синхронизацию Discord была функция, по связке аккаунта Discord с аккаунтом Minecraft (для фильтрации трафика игроков от ботов)

Можно ли реализовать такой функционал в вашем плагине?

**Comment by vanutp** [comment]
See https://github.com/vanutp/tgbridge/issues/35#issuecomment-2439659122
You can subscribe to #16 for updates
