### ISSUE TITLE
Enchancement - add clickable link to open tg chat (/telegram)

### ISSUE THREAD

**Issue by KosyakMakc** [vanutp/tgbridge#44]
I have new players. who can't easily open telegram chat (`/motd` and others command with text print - links is not clickable)
Meaby need special command to provide easy and fast moving to telegram chat, url for this we can store in config.yml

Частенько приходят игроки на сервер, которые имеют сложности с переходом в тг-чат (`/motd` и другие команды с выводом текста - подсвечивают ссылки, но они не кликабельны)
Может стоит реализовать команду для этого чтобы был легкий и быстрый способ перехода в тг-чат, url на чат можем хранить в config.yml

**Comment by vanutp** [comment]
IMO звучит как задача для другого мода. Если сделать фичу для отображения одной ссылки, то как-то слишком специфично, не хочется перегружать мод. Если сделать фичу для отображения любого текста по команде, то не понятно, при чем тут телеграм)
