### ISSUE TITLE
Styled Chat incompatibility

### ISSUE THREAD

**Issue by f1xxd** [vanutp/tgbridge#5]
![image](https://github.com/vanutp/tgbridge/assets/68644513/68518048-09e6-4709-94fb-932a4c2393f3)

**Comment by vanutp** [comment]
What mods do you have installed?

**Comment by f1xxd** [comment]
found out that this is happening due to the mod https://modrinth.com/mod/styled-chat

**Comment by f1xxd** [comment]
/tgbridge dump_lang command doesn't work either (not related to this issue)

**Comment by vanutp** [comment]
> /tgbridge dump_lang command doesn't work either (not related to this issue)

does work for me. There is no command completion when connected to server though (i.e. command appears red while typing, but executes successfully)

**Comment by f1xxd** [comment]
tested with https://modrinth.com/mod/beautified-chat-server
when using it, messages from minecraft doesn't send to telegram. tg->mc work correct
bug with advancements is not reproducible
